all:                                                                            
	#ocamlbuild -use-ocamlfind -package qcheck simpleQcheck.byte                   
	ocamlbuild -use-ocamlfind -package qcheck exercise.byte                                                                            
	#ocamlbuild 
clean:                                                                          
	ocamlbuild -clean  